# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:

  - job_name: 'node'

    static_configs:
      - targets: ['192.168.32.6:9100']

  - job_name: 'openvpn'

    static_configs:
      - targets: ['192.168.32.5:9176']


  - job_name: "synapse"
    scrape_interval: 15s
    metrics_path: "/_synapse/metrics"
    static_configs:
      - targets: ["172.17.0.3:4654"]